spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybox?useSSL=false&characterEncoding=UTF-8&tlsVersion=TLSv1:2&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: admin
    hikari:
      maximum-pool-size: 10
  sql:
    init:
      schema-locations: classpath:sql/schema/**.sql
      data-locations:
        - classpath:sql/data/**.sql
      mode: always
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 3000
      timeout: 3000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    #        default_batch_fetch_size: 100
#        show_sql: false
#        format_sql: true
    open-in-view: false
#  jackson:
#    property-naming-strategy: SNAKE_CASE
#    deserialization:
#      FAIL_ON_NULL_FOR_PRIMITIVES: true

